In [4]:
%load_ext autoreload
%autoreload 2
import activation_function

In [2]:
import numpy as np
x = np.array([0.3, 2.9, 4.0])

In [3]:
activation_function.softmax(x)

array([0.01821127, 0.24519181, 0.73659691])

In [5]:
y = np.array([2, 3, 4])

In [6]:
x * y

array([ 0.6,  8.7, 16. ])

In [7]:
import layer

In [12]:
affine_out = x.copy()
sigmoid = layer.sigmoid()
sigmoid.forward(x)
sigmoid.out

array([0.57444252, 0.94784644, 0.98201379])